name: Automatic Check

on:
  push:
    branches: [ tech-rework ]
  pull_request:
    branches: [ tech-rework ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --production --pure-lockfile    

      - name: Run automatic check
        run: |
          node defaults.js
          node check.js

      - name: Push updated locales
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push 

      - name: Run bundle script
        run: |
          node bundle.js
          cp .gitignore build/.gitignore

      - name: Push bundle to dist branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: tech-rework-dist
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
